/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaPresentacion;

import informacion.Credenciales;
import javax.swing.JOptionPane;

/**
 *
 * @author juanp
 */
public class AccesoNomina extends javax.swing.JFrame {

    /**
     * Creates new form AccesoNomina
     */
    public AccesoNomina() {
        initComponents();
        setLocationRelativeTo(null);
        trans();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nip1 = new resoluciones.nip();
        btlEntrar = new javax.swing.JButton();
        pssnip = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        btlSalir1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        btlLogin1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btlEntrar.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        btlEntrar.setText("Entrar");
        btlEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btlEntrarMouseClicked(evt);
            }
        });
        btlEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlEntrarActionPerformed(evt);
            }
        });

        pssnip.setBackground(new java.awt.Color(255, 153, 51));
        pssnip.setFont(new java.awt.Font("Rockwell", 2, 12)); // NOI18N
        pssnip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pssnipActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Rockwell", 2, 14)); // NOI18N
        jLabel2.setText("NIP:");

        jLabel1.setFont(new java.awt.Font("Old English Text MT", 2, 18)); // NOI18N
        jLabel1.setText("Ventana De Seguridad");

        Salir.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salir.png"))); // NOI18N
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nip1Layout = new javax.swing.GroupLayout(nip1);
        nip1.setLayout(nip1Layout);
        nip1Layout.setHorizontalGroup(
            nip1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nip1Layout.createSequentialGroup()
                .addGroup(nip1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nip1Layout.createSequentialGroup()
                        .addGroup(nip1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nip1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel2)
                                .addGap(27, 27, 27)
                                .addGroup(nip1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pssnip)))
                            .addGroup(nip1Layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(btlEntrar)))
                        .addGap(0, 104, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nip1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        nip1Layout.setVerticalGroup(
            nip1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nip1Layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(nip1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pssnip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(37, 37, 37)
                .addComponent(btlEntrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Salir)
                .addGap(13, 13, 13))
        );

        getContentPane().add(nip1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 400, 300));

        jMenu3.setText("Archivo");

        btlSalir1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        btlSalir1.setText("Salir");
        btlSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlSalir1ActionPerformed(evt);
            }
        });
        jMenu3.add(btlSalir1);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("View");

        btlLogin1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        btlLogin1.setText("Login");
        btlLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlLogin1ActionPerformed(evt);
            }
        });
        jMenu4.add(btlLogin1);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed

        Menu ME= new Menu();
        ME.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_SalirActionPerformed

    private void btlSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlSalir1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btlSalir1ActionPerformed

    private void btlLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlLogin1ActionPerformed
        Acceso AC= new Acceso();
        AC.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btlLogin1ActionPerformed

    private void pssnipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pssnipActionPerformed
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_pssnipActionPerformed

    private void btlEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlEntrarActionPerformed
        
    }//GEN-LAST:event_btlEntrarActionPerformed

    private void btlEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btlEntrarMouseClicked
       
        Credenciales rs=new Credenciales();
       
    
       rs.getNIP();
        
        
        String NP= new String (pssnip.getPassword());
        
        if (NP.equals(rs.getNIP())){
            
            RegistroEmpleados RE= new RegistroEmpleados();
            RE.setVisible(true);
            dispose();

        }
        else{
            JOptionPane.showMessageDialog(this, " NIP Incorrecto ");
            
        }

        
        
        
        
    }//GEN-LAST:event_btlEntrarMouseClicked

    
    public void trans(){
        
    
    Salir.setOpaque(false);
    Salir.setContentAreaFilled(false);
    Salir.setBorderPainted(false);
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccesoNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccesoNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccesoNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccesoNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccesoNomina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salir;
    private javax.swing.JButton btlEntrar;
    private javax.swing.JMenuItem btlLogin1;
    private javax.swing.JMenuItem btlSalir1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private resoluciones.nip nip1;
    private javax.swing.JPasswordField pssnip;
    // End of variables declaration//GEN-END:variables
}
