/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaPresentacion;






import informacion.Credenciales;
import javax.swing.JOptionPane;

/**
 *
 * @author juanp
 */
public class Acceso extends javax.swing.JFrame {

    /**
     * Creates new form Acceso
     */
    public Acceso() {
        initComponents();
        trans();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        NIP = new javax.swing.JPasswordField();
        me1 = new resoluciones.Me();
        Salir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        LBNip = new javax.swing.JLabel();
        btlEntrar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        ACArchivo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsuario.setBackground(new java.awt.Color(255, 153, 51));
        txtUsuario.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 76, 265, -1));

        password.setBackground(new java.awt.Color(255, 153, 51));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 114, 265, -1));

        NIP.setBackground(new java.awt.Color(255, 153, 51));
        getContentPane().add(NIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 152, 265, -1));

        Salir.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salir.png"))); // NOI18N
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        jLabel4.setText("Acceso a Onix Collection");

        lblContraseña.setFont(new java.awt.Font("Rockwell", 2, 14)); // NOI18N
        lblContraseña.setText("Contraseña:");

        lblUsuario.setFont(new java.awt.Font("Rockwell", 2, 14)); // NOI18N
        lblUsuario.setText("Usuario :");

        LBNip.setFont(new java.awt.Font("Rockwell", 2, 14)); // NOI18N
        LBNip.setText("NIP:");

        btlEntrar.setFont(new java.awt.Font("Rockwell", 2, 14)); // NOI18N
        btlEntrar.setText("Entrar");
        btlEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btlEntrarMouseClicked(evt);
            }
        });
        btlEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout me1Layout = new javax.swing.GroupLayout(me1);
        me1.setLayout(me1Layout);
        me1Layout.setHorizontalGroup(
            me1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(me1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(me1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBNip)
                    .addComponent(lblUsuario)
                    .addComponent(lblContraseña))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, me1Layout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addGroup(me1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, me1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(137, 137, 137))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, me1Layout.createSequentialGroup()
                        .addComponent(btlEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        me1Layout.setVerticalGroup(
            me1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, me1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addComponent(lblUsuario)
                .addGap(18, 18, 18)
                .addComponent(lblContraseña)
                .addGap(18, 18, 18)
                .addComponent(LBNip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(me1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btlEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(me1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 470, 270));

        jMenuBar1.setForeground(new java.awt.Color(0, 102, 153));

        ACArchivo.setText("Archivo");
        ACArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACArchivoActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        ACArchivo.add(jMenuItem1);

        jMenuBar1.add(ACArchivo);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btlEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btlEntrarMouseClicked
        

      Credenciales rs=new Credenciales();
       
       String Usuario;
       rs.getContrasena();
       rs.getNIP();
        
        
        
        String pass = new String (password.getPassword());
        String pas= new String (NIP.getPassword());
        
        if (txtUsuario.getText().equals(rs.Usuario)&& pass.equals(rs.getContrasena())&& pas.equals(rs.getNIP())){
            
            Menu ME= new Menu();
            ME.setVisible(true);
            dispose();
         
        }
        else{
            JOptionPane.showMessageDialog(this, " Usuario  / Contraseña y/o NIP incorrectos ");
        
        }

        
        
    }//GEN-LAST:event_btlEntrarMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btlEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlEntrarActionPerformed
        
    }//GEN-LAST:event_btlEntrarActionPerformed

    private void ACArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ACArchivoActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    
    public void trans(){
        
    
    Salir.setOpaque(false);
    Salir.setContentAreaFilled(false);
    Salir.setBorderPainted(false);
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acceso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ACArchivo;
    private javax.swing.JLabel LBNip;
    private javax.swing.JPasswordField NIP;
    private javax.swing.JButton Salir;
    private javax.swing.JButton btlEntrar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblUsuario;
    private resoluciones.Me me1;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
